backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('project.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.urls import path
from project import views

app_name = 'sales'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_view, name='create'),
    path('login/', views.login_view, name='login'),

    path('product/<int:id_product>/<str:name_product>/', views.product, name='product')
]

project/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class ProductForSale(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default=True)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    posted_date = models.DateField(default=timezone.now)
    img = models.ImageField(blank=True, upload_to='images/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.name} {self.value}'

project/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Nome usuario...',
            }
        ),
        label="Nome de usuario"
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'id':'passwordInput',
                'placeholder':'Sua senha...',
            }
        ),
        label="Digite uma senha"
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'id':'passwordInput',
                'placeholder':'Confirme sua senha...',
            }
        ),
        label="Confirmar senha"
    )

    class Meta:
        model = User
        fields = (
            'username', 'password1', 'password2'
        )

project/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from project.forms import RegisterForm

from .models import ProductForSale

def index(request):
    products = ProductForSale.objects.order_by('-id')

    context = {
        'site_title': 'Princiapal',
        'products': products
    }
    return render(request, 'project/index.html', context)

def create_view(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('sales:index')

    context = {
        'site_title': 'Criar',
        'title_form': 'Cadastrar',
        'form': form
    }
    return render(request, 'project/create.html', context)

def login_view(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('sales:index')

    context = {
        'site_title': 'Login',
        'title_form': 'Login',
        'form': form
    }
    return render(request, 'project/login.html', context)

project/views/form_user.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from project.forms import RegisterForm

def create_view(request):
    form = RegisterForm()

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('sales:index')

    context = {
        'site_title': 'Criar',
        'title_form': 'Cadastrar',
        'form': form
    }
    return render(request, 'project/create.html', context)

def login_view(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('sales:index')

    context = {
        'site_title': 'Login',
        'title_form': 'Login',
        'form': form
    }
    return render(request, 'project/login.html', context)

project/views/index_view.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.core.paginator import Paginator
from project.models import ProductForSale, Category

def index(request):
    products = ProductForSale.objects.order_by('-id')
    paginator = Paginator(products, 4)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    categoryes = Category.objects.order_by('-id')

    context = {
        'site_title': 'Principal',
        'products': page_obj,
        'categoryes': categoryes
    }
    return render(request, 'project/index.html', context)

def product(request, id_product, name_product):
    obj_product = get_object_or_404(ProductForSale, pk=id_product)
    context = {
        'site_title': f'Produto {name_product}',
        'product': obj_product
    }
    return render(request, 'project/product.html', context)

project/templates/project/create.html
{% extends "project/global/base.html" %}
{% block content %}
    {% include "project/partials/_form.html" %}
{% endblock content %}

project/templates/project/global/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>{{ site_title }} - Vendas</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

project/templates/project/index.html
{% extends "project/global/base.html" %}
{% block content %}
    {% include "project/partials/_header.html" %}
    <main class="py-5 container text-light">
        {% for categorys in categoryes %}
            <div class="bg-dark rounded p-4 my-4">
                <h1>Produtos relacionados com {{ categorys.name }}</h1>
                <article class="row text-dark">
                    {% for product in products %}
                        {% if categorys.id == product.category.id %}
                                <a 
                                    href="{% url "sales:product" product.id product.name|cut:"/" %}" 
                                    class="col m-1 bg-light text-dark link-offset-2 link-underline link-underline-opacity-0 rounded row"
                                >
                                    <div class="text-center mt-auto">
                                        <img class="img-fluid" width="100" src="{{ product.img.url }}" alt="img">                                          
                                    </div>
                                    <div class="mt-auto">
                                        <h6 class="text-truncate text-break m-1" style="max-width: 210px;">
                                            {{ product.name }}
                                        </h6>
                                        <p class="m-2 fs-4">
                                            R$ {{ product.value }}
                                        </p>  
                                    </div>
                                </a>
                        {% endif %}
                    {% endfor %}
                </article>
                <a href="#" class="btn btn-outline-light mt-2">Veja mais...</a>
            </div>
        {% endfor %}    
    </main>
    {% include "project/partials/_footer.html" %}
{% endblock content %}

project/templates/project/login.html
{% extends "project/global/base.html" %}
{% block content %}
    {% include "project/partials/_form.html" %}
{% endblock content %}

project/templates/project/partials/_footer.html
<footer>
    Fundo
</footer>

project/templates/project/partials/_form.html
<form action="{% url "sales:index" %}" method="POST">
    <h1>{{ title_form }}</h1>
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.is_for_label }}">{{field_label}}</label>
            {{ field }}
            {{ field.errors }}
        </div>
    {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">
                Enviar
            </button>
        </div>
</form>

project/templates/project/partials/_header.html
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <i class="bi bi-globe-americas fs-2"></i>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-white">Categorias</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Ofertas</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Historico</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Supermercado</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Moda</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="/" method="GET">
                {% csrf_token %}
                <input type="search" name="q" required class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="text-end">
                    <a href="/" class="btn btn-outline-light me-2">Sair</a>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url "sales:login" %}" class="btn btn-outline-light me-2">Login</a>
                    <a href="{% url "sales:create" %}" class="btn btn-warning">Cadastrar-se</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>

project/templates/project/product.html
{% extends "project/global/base.html" %}
{% load static %}
{% block content %}
    {% include "project/partials/_header.html" %}
    <main class="text-light bg-light-d mt-5 container rounded p-4">
        <section class="row">
            <div class="col-sm-8 row">
                <div class="col-sm-2">
                    <ul class="nav-list">
                        <li class="list-img">
                            <img class="img-fluid" src="{{ product.img.url }}" width="90" alt="{{ product.img.url }}">
                        </li>
                        <li class="list-img">
                            <img class="img-fluid" src="{{ product.img.url }}" width="90" alt="{{ product.img.url }}">
                        </li>
                        <li class="list-img">
                            <img class="img-fluid" src="{{ product.img.url }}" width="90" alt="{{ product.img.url }}">
                        </li>
                    </ul>
                </div>
                <div class="col-sm-10">
                    <img class="img-fluid" width="400" src="{{ product.img.url }}" alt="{{ product.img.url }}">
                </div>
            </div>
            <div class="col-sm-4 border rounded">
                <div class="pt-2">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <label for="CEP">CEP:
                            <input class="form-control" type="text" name="CEP" id="CEP">
                            <button class="mt-2 btn btn-outline-light" type="submit">
                                Enviar
                            </button>
                        </label>
                    </form>
                </div>
                <div class="lh-1">
                    <p class="lead pt-2">
                        Chegará <span id="deliveryDayInformation"></span>
                    </p>
                    <p class="lead fs-6 text-secondary">
                        Comprado dentro das proximas
                    </p>
                    <span id="dayHour">HORAS</span> <span><a href="#" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">mais formas de entrega...</a></span>
                </div>
            </div>
        </section>
    </main>

    <script src="{% static "js/product.js" %}"></script>
{% endblock content %}